In [1]:
import numpy as np

In [11]:
#Matrix Addition
A=np.array([[2,3],[4,5]])

B=np.array([[5,2],[1,2]])

sum=A+B
print(sum)

[[7 5]
 [5 7]]


In [7]:
print(A)

[[2 3]
 [4 5]]


In [8]:
print(B)

[[5 2]
 [1 2]]


In [9]:
A.shape

(2, 2)

In [10]:
B.shape

(2, 2)

In [12]:
matrix_1=np.random.randint(10,size=(3,3))
matrix_2=np.random.randint(32,size=(3,3))

In [13]:
sum=np.add(matrix_1,matrix_2)

In [14]:
print(sum)

[[29 25 16]
 [24 19 27]
 [29 19 10]]


In [15]:
#Matrix Substraction
A=np.array([[2,3],[4,5]])

B=np.array([[5,2],[1,2]])

difference=A-B
print(difference)

[[-3  1]
 [ 3  3]]


In [16]:
matrix_1=np.random.randint(10,size=(3,3))
matrix_2=np.random.randint(20,size=(3,3))

In [17]:
print(matrix_1)

[[2 0 4]
 [5 8 0]
 [1 6 5]]


In [18]:
print(matrix_2)

[[10 13 18]
 [14  5 17]
 [19  5 18]]


In [19]:
diff=np.subtract(matrix_1,matrix_2)

In [20]:
print(diff)

[[ -8 -13 -14]
 [ -9   3 -17]
 [-18   1 -13]]


In [21]:
#multiplying matrix with scalar

a=5
y=np.random.randint(10,size=(3,3))

print(y)

[[7 4 4]
 [0 8 7]
 [2 6 3]]


In [23]:
product=np.multiply(a,y)
print(product)

[[35 20 20]
 [ 0 40 35]
 [10 30 15]]


In [24]:
x=np.random.randint(20,size=(3,3))
y=np.random.randint(10,size=(3,3))

In [25]:
print(x)

[[ 5  7 18]
 [13 17 10]
 [10  5 13]]


In [26]:
print(y)

[[2 3 7]
 [8 5 0]
 [2 7 7]]


In [28]:
product=np.dot(x,y)
print(product)

[[102 176 161]
 [182 194 161]
 [ 86 146 161]]


In [29]:
product.shape

(3, 3)