In [1]:
import numpy as np

In [3]:
matrix_1=np.array([[2,3],[6,7]])
print(matrix_1)

[[2 3]
 [6 7]]


In [4]:
matrix_1.shape

(2, 2)

In [5]:
matrix_2=np.array([[10,35,43],[6,7,8]])
print(matrix_2)

[[10 35 43]
 [ 6  7  8]]


In [6]:
matrix_2.shape

(2, 3)

In [7]:
#random value
random_matrix=np.random.rand(3,3)
print(random_matrix)

[[0.92158286 0.84484423 0.18336309]
 [0.84022502 0.10142628 0.64138413]
 [0.15913343 0.46147309 0.70548566]]


In [11]:
#random integer value
random_integer_matrix=np.random.randint(4,20,size=(3,3))
print(random_integer_matrix)

[[ 6 17  9]
 [ 7 10 18]
 [11  4  7]]


In [14]:
#matrix with all value is 1
matrix_3=np.ones((3,3),dtype=int)
print(matrix_3)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [15]:
#matrix with all value is 0
matrix_3=np.zeros((3,3),dtype=int)
print(matrix_3)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [16]:
identity_matrix=np.eye(3,3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [17]:
#Transpose matrix
a=np.random.randint(10,size=(3,3))
print(a)

[[7 0 7]
 [0 9 5]
 [3 7 0]]


In [19]:
transpose_a=np.transpose(a)
print(transpose_a)

[[7 0 3]
 [0 9 7]
 [7 5 0]]
